In [1]:
from collections import Counter

import category_encoders as ce
import matplotlib.pyplot as plt
from scipy.stats import skewnorm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import spacy
from sklearn.preprocessing import LabelEncoder

from sklearn.cluster import KMeans
from create_dataset import ds

# Feature engineering

Adding columns or transform existing columns
- this includes the target (target transformation)

## How can I generate features?

Domain knowledge
- use business insight -> features

Exploratory data analysis

Build features from features
- ratios
- polynomials
- log / exponentials / sigmoids
- Fourier / Laplace transforms

## Data leakage

Feature available during training that isn't available during testing / production time

Duplicates in the train & test set

Training / learning statistics from the test set
- common mistake to refit normalization / standardization

Feature engineering can often cause data leakage
- mean target encoding on the entire dataset, before splitting test & train

## Nominal vs ordinal

Nominal (no order) versus ordinal (order)

Some methods place order onto a nominal series during the encoding

## Transform from continuous to categorical

On the target 
- moving from a regression to classification problem 
- key thing to ask - how do we use our prediction in our business problem

On features 
- removes noise (& maybe signal)

In [2]:
ds

   customers-category  contract-length location
0                   A             10.0       us
1                   A              9.0       us
2                   A              9.0       us
3                   B             20.0       nz
4                   B             30.0      NaN
5                   B             10.0       nz
6                   C              NaN       nz
7                   C              5.0       nz
8                   C              NaN       us
9                 NaN              1.0       nz
10                  C            100.0       nz

In [ ]:
#### ---- drop null values
# df <--- Pandas dataframe
df.dropna(axis=0) # dropping null values
df.fillna(0)  # replace all null values with 0

In [36]:
#### loc & iloc -- locate values in your dataframe
ds.iloc[:,1]

0      10.0
1       9.0
2       9.0
3      20.0
4      30.0
5      10.0
6       NaN
7       5.0
8       NaN
9       1.0
10    100.0
Name: contract-length, dtype: float64

In [37]:
ds.loc[:, 'contract-length']

0      10.0
1       9.0
2       9.0
3      20.0
4      30.0
5      10.0
6       NaN
7       5.0
8       NaN
9       1.0
10    100.0
Name: contract-length, dtype: float64

In [3]:
pd.cut(ds.loc[:, 'contract-length'].fillna(0), bins=4)

0      (-0.1, 25.0]
1      (-0.1, 25.0]
2      (-0.1, 25.0]
3      (-0.1, 25.0]
4      (25.0, 50.0]
5      (-0.1, 25.0]
6      (-0.1, 25.0]
7      (-0.1, 25.0]
8      (-0.1, 25.0]
9      (-0.1, 25.0]
10    (75.0, 100.0]
Name: contract-length, dtype: category
Categories (4, interval[float64, right]): [(-0.1, 25.0] < (25.0, 50.0] < (50.0, 75.0] < (75.0, 100.0]]

## Dealing with categorical variables

Machine always think in numbers
- all categorical features need to be transformed into numbers at somepoint
- most ML algorithms get upset if you don't do it - some will do it on the fly

## One hot encoding

- curse of dimensionality makes dimensionality increase exponential
- lose the explicit relationship of the feature (model now just sees a lot of columns, and has to learn their relationship)

There are a few ways to do one-hot encoding in the Python
- `sklearn.preprocessing.OneHotEncoder()`
- `pd.get_dummies()`

Recommend `sklearn.preprocessing.OneHotEncoder()`
- creates a stateful transformer that can be reused (i.e. on the test data)
- using `pd.get_dummies`, you are hoping that the columns will be encoded in the same way at test time

In [4]:
ds

   customers-category  contract-length location
0                   A             10.0       us
1                   A              9.0       us
2                   A              9.0       us
3                   B             20.0       nz
4                   B             30.0      NaN
5                   B             10.0       nz
6                   C              NaN       nz
7                   C              5.0       nz
8                   C              NaN       us
9                 NaN              1.0       nz
10                  C            100.0       nz

In [11]:
from sklearn.preprocessing import OneHotEncoder

#  note that I use a missing value token here
cat = ds.loc[:, 'customers-category'].to_frame().fillna('missing')

#  will by default return a sparse matrix - you can turn this off
enc = OneHotEncoder(sparse_output=False)
enc.fit_transform(cat)

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

## Label encoding

- `0, 1, 2, 3`
- is an ordinal encoding - even if feature is not ordinal, you are imposing this structure on the data

Decision trees sort the data based on the feature being split on
- this makes the decision boundary meaningful
- inherently ordinal

In [14]:
enc = LabelEncoder()
enc.fit_transform(cat)

/Users/samson.afolabi/opt/anaconda3/envs/f2m/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 2])

## Mean encode

- put the training data average for the target for that class
- could also use other statistics like median, quantiles or variance

The code below will mean encode a categorical feature using the average of another column (often the target):

In [15]:
store1 = pd.DataFrame(
        {'store': ['A'] * 3,
         'Sales': [100, 200, 300],
         'noise': [0, 0, 0]}
    )

store2 = pd.DataFrame(
        {'store': ['B'] * 3,
         'Sales': [10, 20, 30],
         'noise': [0, 0, 0]}
    )

data = pd.concat([store1, store2], axis=0)
data

  store  Sales  noise
0     A    100      0
1     A    200      0
2     A    300      0
0     B     10      0
1     B     20      0
2     B     30      0

In [22]:
def mean_encode(data, col, on):
    data = data.copy()

    # Compute mean target per category
    means = data.groupby(col)[on].mean()

    # Preserve original column
    data[f"{col}-original"] = data[col]

    # Apply encoding
    data[col] = data[col].map(means)

    # Fill unseen categories with global mean
    data[col] = data[col].fillna(data[on].mean())

    return data


#define data
store1 = pd.DataFrame(
        {'store': ['A'] * 3,
         'Sales': [100, 200, 300],
         'noise': [0, 0, 0]}
    )

store2 = pd.DataFrame(
        {'store': ['B'] * 3,
         'Sales': [10, 20, 30],
         'noise': [0, 0, 0]}
    )

data = pd.concat([store1, store2], axis=0)
data = mean_encode(data, col='store', on='Sales')

data

   store  Sales  noise store-original
0  200.0    100      0              A
1  200.0    200      0              A
2  200.0    300      0              A
0   20.0     10      0              B
1   20.0     20      0              B
2   20.0     30      0              B

## Binary encoding

Encoding the string using it's binary (0110100 etc) representation

In Python we can do this using the `bin()` builtin:

In [23]:
bin(2)

'0b10'

In [24]:
bin(16)

'0b10000'

The `category_encoders` library can do this for us:

In [25]:
data = ['A', 'BB', 'B', 'A', 'C', 'D', 'A', 'E']
data = [1,2,3,1,4,5,1,6]

enc = ce.BinaryEncoder()  #similar to onehot, but stores categories as binary bitstrings.

print('{} classes'.format(len(set(data))))

pd.concat([enc.fit_transform(data), pd.DataFrame(data, columns=['data'])], axis=1)

6 classes
Warning: No categorical columns found. Calling 'transform' will only return input data.

   0  data
0  1     1
1  2     2
2  3     3
3  1     1
4  4     4
5  5     5
6  1     1
7  6     6

## Frequency encoding

Encode the categorical feature based on their relative frequency
- probability of seeing this category
- tell the model about rare categories
- but you can't distinguish categories with the same frequency (unlikely in very large datasets)

In [26]:
data = ['A', 'B', 'A', 'C', 'D', 'A', 'E']
counter = Counter(data)
freq_enc = [counter[x] / len(data) for x in data]

pd.DataFrame(
    {'data': data,
     'freq_enc': freq_enc}
)

  data  freq_enc
0    A  0.428571
1    B  0.142857
2    A  0.428571
3    C  0.142857
4    D  0.142857
5    A  0.428571
6    E  0.142857

### Others

- hint your model as much as possible.

In [27]:
data = pd.DataFrame(
    {'sales': [10, 50, 100], 'year': [2012, 2013, 2014]}
)

data.loc[:, 'last-year-sales-feature'] = data.loc[:, 'sales'].shift()
data.loc[:, 'model-target'] = data.loc[:, 'sales'].diff()

data

   sales  year  last-year-sales-feature  model-target
0     10  2012                      NaN           NaN
1     50  2013                     10.0          40.0
2    100  2014                     50.0          50.0

## Dimensionality reduction

### PCA

Both forms of dimensionality reduction, that can create new columns
- these can sit alongside or replace the high dimensional data

### Clustering

Can be used to create a new feature:

In [28]:
data = pd.DataFrame([np.random.uniform(0, x, 1000) for x in range(1, 10)]).T

mdl = KMeans(3)
mdl.fit(data)
data.loc[:, 'cluster'] = mdl.labels_ 

data.head()

,0,1,2,3,4,5,6,7,8,cluster
0,0.622377,1.182589,2.700959,2.384133,4.750379,4.245675,0.946639,4.994770,0.999720,0
1,0.751732,0.228681,1.448234,3.636492,3.712665,5.830346,1.354877,6.651384,7.340201,1
2,0.225846,1.240940,2.662532,1.992499,2.097042,1.777708,2.141159,7.002728,4.480253,0
3,0.471331,1.885260,1.009215,1.465014,2.363566,1.250830,3.295755,2.456491,0.389741,2
4,0.851894,0.667372,2.293358,3.731293,4.989380,2.021585,2.320862,3.922473,2.038935,0

## Datetime

### Month, year, day columns

These can then be either be label / one-hot encoded

In [29]:
data = pd.DataFrame(
    {'date': pd.date_range('01-01-2018', '02-01-2018', freq='1h')}
)

data.loc[:, 'month'] = data.loc[:, 'date'].dt.month
data.loc[:, 'minute'] = data.loc[:, 'date'].dt.minute

data.head()

                 date  month  minute
0 2018-01-01 00:00:00      1       0
1 2018-01-01 01:00:00      1       0
2 2018-01-01 02:00:00      1       0
3 2018-01-01 03:00:00      1       0
4 2018-01-01 04:00:00      1       0

## Time series decomposition

Seasonality, trend can become features

More important than other areas to ask the question
- what will I have available at test time?
- example of weather versus weather forecasts

## References

[Feature Engineering - Elite Data Science](https://elitedatascience.com/feature-engineering)

[Feature Engineering for ML](https://towardsdatascience.com/feature-engineering-for-machine-learning-3a5e293a5114)